### ISSUE TITLE
Registro modificar cuenta 02/04/2023

### ISSUE THREAD

**Issue by dDevTech** [dDevTech/tapas-top-frontend#31]
**Requiere actualización de la api del backend settings/updateAccount**

- Modificar el post request para que obtenga la informacion de todos los campos y los muestre en settings del perfil utilizando la nueva api  api/getAccount. Los campos deben rellenarse con la informacion del usuario completa (todos)
- Modificar el campo foto para sea un campo de texto para introducir una URL
- Modificar el post request  settings/updateAccount  para pasar la informacion adicional opcional (foto, direccion , género ...)

**Comment by ilaygalron** [comment]
Los campos ya se actualizan y que mantienen en el formulario. Tengo que esperar a que el backend actualice la petición GET api/account para mandar tambien los datos del address.
