### ISSUE TITLE
Más valoradas obtener información y presentar en lista 24/04/2023

### ISSUE THREAD

**Issue by dDevTech** [dDevTech/tapas-top-frontend#43]
- Requiere #41 diseño de más valorada

Hacer petición a API para obtener listado de tapas ordenadas por valoración con la información de estas aplicando los filtros superiores

**Comment by lucia-jiang** [comment]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/104275311/234527904-347a4eb7-b119-41cc-adef-1c39310ebfc8.png">
debería añadir un botón de limpiar filtros??
