### ISSUE TITLE
Añadir posibilidad de poner tapa favorita

### ISSUE THREAD

**Issue by dDevTech** [dDevTech/tapas-top-frontend#50]
- Requiere #49 
En el menú degustaciones al buscar una tapa y mostrar coincidencias
- Añadir un botón con icono de favorito para poder añadirla como favorito. Este botón será funcional y cambiará de color si está como favorito o no. (**REALIZADO NO HACE FALTA**)
Por ello debemos tener en cuenta las siguientes acciones:
- Peticion backend de añadir a favorito de usuario o quitar de favorito
- Al buscar la tapa debemos también ver si está en favoritos para poder mostrar el icono como ya en favorito

**Comment by 8davidp** [comment]
He creado un componente para otra tarea que se va a usar como modelo en las tres pantallas de tapa. Hay que hacer la funcionalidad en ese componente (tastingElement.tsx)
