### ISSUE TITLE
Correción rutas y completar 25/03/2023

### ISSUE THREAD

**Issue by dDevTech** [dDevTech/tapas-top-frontend#60]
-  En la ventana prinicipal boton de introducir nueva degustacion redirigir a /newDish
- Boton ver todas las degustaciones en Home que te redirija a /myTastings
-  Chequear que todas las rutas funcionas correctamente y no falta ninguna

**Comment by lucia-jiang** [comment]
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/104275311/234598223-245c6e5d-a151-407a-adb0-ac0a8d348904.png">
El botón de ver degustaciones actualmente despliega en la misma página todas las tapas. Lo dejamos así o preferimos que redirija a /myTastings?
