### ISSUE TITLE
Mejorar problemas de diseño página principal Home

### ISSUE THREAD

**Issue by dDevTech** [dDevTech/tapas-top-frontend#65]
Corregir fallos en HOME sin login

- Imagen rota (aparezca una)
- Quita barra de desplazamiento y que se ajusten todos los elementos a toda la pantalla. Botones centrado
- 
![image](https://user-images.githubusercontent.com/18512841/232816328-a5705ecd-f805-4f9f-b1cc-a1b2c6d001dc.png)

Corregir fallos en HOME con login
- Pais y ciudad unificados de manera que sea Ubicacion: Madrid, España
- Tipo de establecimiento no es necesario
- En ventanas pequeñas se corta el texto
- 
![image](https://user-images.githubusercontent.com/18512841/232816604-be003f88-4cc6-41be-9eea-9b3090ec46c2.png)

**Comment by 8davidp** [comment]
Corregida la imagen. Cambio de formato a png compatible con los buscadore.
Ajustado las propiedades css de los botones y la cita para evitar overflow
Descripciones de restaurante corregidas
Overflow de descripción ajustada
